const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Follow,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Geral_Event7_Act2,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{PlanoDeFundoEmBlocos: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Kris: 0},
	{Teclado: 0},
	{Sólido: 0},
	{bloco: 0},
	{chao: 0},
	{caixa: 0},
	{barril: 0},
	{luz: 0},
	{cristal: 0},
	{espinhos: 0},
	{entrada: 0},
	{txtContador: 0},
	{Seguir: 0},
	{Senóide: 0},
	{Sombra: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{logo: 0},
	{btnJogar: 0},
	{jogar: 0},
	{Mouse: 0},
	{Navegador: 0},
	{nuvem: 0},
	{montanha: 0},
	{PERIGO: 0},
	{LAVA: 0},
	{pedra: 0},
	{montanhas2: 0},
	{Sprite2: 0},
	{Áudio: 0},
	{btnJogarNovamente: 0},
	{btnSair: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{btnPular: 0},
	{cristaisColetados: 0},
	{velocidadeSombra: 0},
	{vidas: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Kris: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	bloco: class extends self.ISpriteInstance {},
	chao: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	barril: class extends self.ISpriteInstance {},
	luz: class extends self.ISpriteInstance {},
	cristal: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	entrada: class extends self.ISpriteInstance {},
	txtContador: class extends self.ITextInstance {},
	Sombra: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	logo: class extends self.ISpriteInstance {},
	btnJogar: class extends self.ITextInstance {},
	jogar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Navegador: class extends self.IInstance {},
	nuvem: class extends self.ISpriteInstance {},
	montanha: class extends self.ISpriteInstance {},
	PERIGO: class extends self.ISpriteInstance {},
	LAVA: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	montanhas2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	btnJogarNovamente: class extends self.ITextInstance {},
	btnSair: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	btnPular: class extends self.ITextInstance {}
}